export { default as authRoutes } from './auth.route'
export { default as deckRoutes } from './deck.route'
export { default as cardRoutes } from './card.route'
export { default as wordRoutes } from './word.route'
export { default as definitionRoutes } from './definition.route'
